#!/bin/bash

mysql -u root -p"$MYSQL_ROOT_PASSWORD" << EOF
CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE\`;
CREATE DATABASE IF NOT EXISTS \`$DB_BOT_DATABASE\`;

CREATE USER '$DB_USERNAME'@'%' IDENTIFIED WITH caching_sha2_password BY '$DB_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES ON \`$DB_DATABASE\`.* TO '$DB_USERNAME'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES ON \`$DB_BOT_DATABASE\`.* TO '$DB_USERNAME'@'%';

CREATE USER '$DB_BOT_USERNAME'@'%' IDENTIFIED WITH caching_sha2_password BY '$DB_BOT_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, LOCK TABLES ON \`$DB_BOT_DATABASE\`.* TO '$DB_BOT_USERNAME'@'%';
EOF
